package tokencrypto

import (
	"encoding/base64"
	"testing"
)

// Generated by apps/api's real crypto.util.ts encrypt() (Node crypto,
// AES-256-GCM) — proves this package is byte-for-byte wire-compatible with
// what NestJS actually writes to amazon_sp_accounts.refresh_token.
const (
	nodeKeyB64        = "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc="
	nodePlaintext     = "Atzr|IwEBIExampleRefreshToken1234567890"
	nodeCiphertextB64 = "EpJy1BwxHzjnjVPPVGwNdJAmyMIBkcBG63V7c4L5fqay8oDkl+PYrdaaD/INy3UYU/jKZzS17UHAVEM7m7PKi6VAXw=="
)

func TestDecrypt_MatchesNodeImplementation(t *testing.T) {
	key, err := base64.StdEncoding.DecodeString(nodeKeyB64)
	if err != nil {
		t.Fatalf("decode key: %v", err)
	}

	got, err := Decrypt(key, nodeCiphertextB64)
	if err != nil {
		t.Fatalf("Decrypt() error: %v", err)
	}
	if got != nodePlaintext {
		t.Fatalf("Decrypt() = %q, want %q", got, nodePlaintext)
	}
}

func TestEncryptDecrypt_RoundTrip(t *testing.T) {
	key := make([]byte, 32)
	for i := range key {
		key[i] = byte(i)
	}

	plaintext := "some-refresh-token-value"
	ciphertext, err := Encrypt(key, plaintext)
	if err != nil {
		t.Fatalf("Encrypt() error: %v", err)
	}
	if ciphertext == plaintext {
		t.Fatalf("Encrypt() did not transform plaintext")
	}

	got, err := Decrypt(key, ciphertext)
	if err != nil {
		t.Fatalf("Decrypt() error: %v", err)
	}
	if got != plaintext {
		t.Fatalf("round trip = %q, want %q", got, plaintext)
	}
}

func TestEncrypt_RandomIVProducesDifferentCiphertext(t *testing.T) {
	key := make([]byte, 32)
	for i := range key {
		key[i] = byte(i)
	}

	a, err := Encrypt(key, "same-value")
	if err != nil {
		t.Fatalf("Encrypt() error: %v", err)
	}
	b, err := Encrypt(key, "same-value")
	if err != nil {
		t.Fatalf("Encrypt() error: %v", err)
	}
	if a == b {
		t.Fatalf("expected different ciphertext for repeated encryption of the same plaintext")
	}
}

func TestDecrypt_TamperedCiphertextFails(t *testing.T) {
	key := make([]byte, 32)
	for i := range key {
		key[i] = byte(i)
	}

	ciphertext, err := Encrypt(key, "sensitive-token")
	if err != nil {
		t.Fatalf("Encrypt() error: %v", err)
	}
	raw, err := base64.StdEncoding.DecodeString(ciphertext)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	raw[len(raw)-1] ^= 0xFF
	tampered := base64.StdEncoding.EncodeToString(raw)

	if _, err := Decrypt(key, tampered); err == nil {
		t.Fatalf("expected Decrypt() to fail on tampered ciphertext")
	}
}

func TestDecrypt_WrongKeySizeFails(t *testing.T) {
	if _, err := Decrypt([]byte("too-short"), "irrelevant"); err == nil {
		t.Fatalf("expected error for a non-32-byte key")
	}
}
